name: wallbay
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  json_annotation: ^3.0.0
  url_launcher: ^5.1.2
  uni_links: ^0.2.0
  shared_preferences: ^0.5.3+4
  cached_network_image: 2.0.0-rc
  flutter_advanced_networkimage: any
  flutter_spinkit: ^3.1.0
  color: any
  dio: any
  shimmer: ^1.0.0
  share: ^0.6.2+1
  bottom_navy_bar: ^5.1.0
  unicorndial: ^1.1.5
  flutter_staggered_grid_view: ^0.3.0
  permission_handler: ^3.2.0
  image_downloader: ^0.18.1
  wallpaper: ^1.0.0
  sqflite: ^1.1.6
  photo_view: ^0.4.2
  provider: ^3.1.0+1
  cloud_firestore: 0.12.9+6
  firebase_remote_config: ^0.2.0+7
  data_connection_checker: ^0.3.4
  connectivity: ^0.4.3+1








dev_dependencies:
  build_runner: ^1.6.6
  # flutter packages pub run build_runner build lib
  # flutter pub run build_runner watch
  # pub run build_runner watch
  json_serializable: ^3.2.0
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
      

  uses-material-design: true
