name: wallbay
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  json_annotation: ^3.0.0
  url_launcher: ^5.1.2
  uni_links: ^0.2.0
  shared_preferences: ^0.5.3+4
  cached_network_image: ^1.1.1
  flutter_advanced_networkimage: any
  flutter_spinkit: ^3.1.0
  color: any
  dio: any
  shimmer: ^1.0.0
  share: ^0.6.2+1
  bottom_navy_bar: ^5.1.0
  unicorndial: ^1.1.5
  flutter_staggered_grid_view: ^0.3.0
  permission_handler: ^3.2.0
  image_downloader: ^0.18.1
  wallpaper: ^1.0.0






dev_dependencies:
  build_runner: ^1.6.6
  # flutter packages pub run build_runner build lib
  # flutter pub run build_runner watch
  # pub run build_runner watch
  json_serializable: ^3.2.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

